### ISSUE TITLE
Excluding Datasets in Project

### ISSUE THREAD

**Issue by tazy7** [ocadotechnology/bbq#115]
Hi is it possible to exclude datasets in a project or is just projects that can be excluded from backup?

**Comment by radkomateusz** [comment]
Hello, currently bbq supports only blacklisting on projects level.

**Comment by tazy7** [comment]
Thanks for the quick reply, is there anything in your roadmap to do this?

**Comment by radkomateusz** [comment]
Currently no, as deciding what would be backed up on project level is sufficient for us. But we are open for any contribution. 

Nevertheless, there is a possible workaround to achieve your goal and performing backup for only chosen datasets. What you need to do is to share chosen dataset with bbq service account (with 'can view' permission) and assign 'Browser' role on dataset's project also (but without BQ Viewer role).  This will cause that bbq will backup only datasets shared with mentioned service account. 
Unfortunately, this workaround works as whitelisting, not as blacklisting specific datasets.

**Comment by tazy7** [comment]
Thank you for the suggestion around sharing, will give this a try.
